[package]
name = "esp32s3-cam-qr-rs"
version = "0.1.0"
authors = ["tmpk <>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "esp32s3-cam-qr-rs"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"

[features]
default = []
loop=[]

experimental = ["esp-idf-svc/experimental"]

[dependencies]
log = "0.4"
esp-idf-svc = "0.51"
rxing = { version = "0.8.2", default-features = false }

esp-camera-rs = { git = "https://github.com/tmpk13/esp-camera-rs", branch = "Config-Access" }
esp-idf-hal = "0.45.2"
esp-idf-sys = "0.36.1"
mipidsi = "0.9.0"
embedded-graphics = "0.8.1"
esp32-nimble = "0.11.1"
gc9a01-rs = "0.4.2"
embedded-graphics-framebuf = "0.5.0"



# --- Optional Embassy Integration ---
# esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }

# If you enable embassy-time-driver, you MUST also add one of:

# a) Standalone Embassy libs ( embassy-time, embassy-sync etc.) with a foreign async runtime:
# embassy-time = { version = "0.4.0", features = ["generic-queue-8"] } # NOTE: any generic-queue variant will work

# b) With embassy-executor:
# embassy-executor = { version = "0.7", features = ["executor-thread", "arch-std"] }

# NOTE: if you use embassy-time with embassy-executor you don't need the generic-queue-8 feature

# --- Temporary workaround for embassy-executor < 0.8 ---
# esp-idf-svc = { version = "0.51", features = ["embassy-time-driver", "embassy-sync"] }
# critical-section = { version = "1.1", features = ["std"], default-features = false }

[build-dependencies]
embuild = "0.33"

# esp camera bindings
# https://docs.esp-rs.org/esp-idf-hal/esp_idf_sys/index.html#remote-components-idf-component-registry
[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp32-camera", version = "2.0.7" }
bindings_header = "bindings.h"
bindings_module = "camera"

